### ISSUE TITLE
Unable to jump while forced to crouch but not holding the crouch key

### ISSUE THREAD

**Issue by drjaska** [chovelyoukai/defragmmod#7] opened 2021-08-08 00:20 UTC
As of now players are unable to jump while they have geometry/something above their head while they are crouched which forces them to duck regardless if they are holding the crouch input key or not.

History of the suspected bug causing line:
```
	if (mv->m_nButtons & IN_DUCK)
	if (mv->m_nButtons & IN_DUCK && !sv_crouchjump.GetBool())
	
	if (mv->m_nButtons & IN_DUCK && !sv_crouchjump.GetBool())
	if (player->GetFlags() & FL_DUCKING && !sv_crouchjump.GetBool() || !DFCanUnDuck())
	
	if (player->GetFlags() & FL_DUCKING && !sv_crouchjump.GetBool() || !DFCanUnDuck())
	if (player->GetFlags() & FL_DUCKING && (!sv_crouchjump.GetBool() || !DFCanUnDuck()))
	
	if (player->GetFlags() & FL_DUCKING && (!sv_crouchjump.GetBool() || !DFCanUnDuck()))
	if ((mv->m_nButtons & IN_DUCK) && !sv_crouchjump.GetBool() || (player->GetFlags() & FL_DUCKING))
	
	if ((mv->m_nButtons & IN_DUCK) && !sv_crouchjump.GetBool() || (player->GetFlags() & FL_DUCKING))
	if (((mv->m_nButtons & IN_DUCK) && !sv_crouchjump.GetBool()) || (player->GetFlags() & FL_DUCKING))
```

**Comment by chovelyoukai** [comment] 2021-08-08 01:10
duplicate of #2

**Closed by chovelyoukai** 2021-08-08 01:10 UTC
Labels: duplicate
